rango.tests_chapter9.Chapter9ViewTests.test_login_redirects_to_index
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter10.Chapter10ViewTests.test_about_page_shows_number_of_visits
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter10.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_category_page_using_template
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_url_reference_in_index_page_when_not_logged
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter10.Chapter10ViewTests.test_index_shows_number_of_visits
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter10.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_category_contains_link_to_add_page
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter10.Chapter10SessionTests.test_user_number_of_access_and_last_access_to_index
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter10.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_base_template_exists
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_category_page_displays_empty_message
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter4.Chapter4ViewTest.test_about_contain_image
F
======================================================================
FAIL: test_about_contain_image (rango.tests_chapter4.Chapter4ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter4.py", line 51, in test_about_contain_image
    self.assertIn('img src="/static/images/', response.content.decode('ascii'))
AssertionError: 'img src="/static/images/' not found in u'<!DOCTYPE html>\n <!-- New line -->\n\n<html>\n\t<head>\n\t\t<title>Rango</title>\n\t</head>\n\t\n\t<body>\n\t\t<h1>Rango says....</h1>\n\t\t<div>\n\t\t\tWelcome to the about page <br />\n\t\t\t<strong>This tutorial has been put together by Adam Christie</strong> <br />\n\t\t</div>\n\t\t<div>\n\t\t\t<a href="/rango/">Index</a><br />\n\t\t\t<img src="/media/cat.jpg "/>\n\t\t</div>\n\t</body>\n</html>\n'

----------------------------------------------------------------------
Ran 1 test in 0.090s

FAILED (failures=1)
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_pages_using_templates
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter5.Chapter5ModelTests.test_create_pages_for_categories
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter5.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_index_displays_five_most_viewed_pages
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_access_category_that_does_not_exists
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter10.Chapter10ViewTests.test_visit_number_is_passed_via_context
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter10.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_category_page_displays_pages
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter9.Chapter9ViewTests.test_login_provides_error_message
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_url_reference_in_index_page_when_logged
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_index_contains_link_to_categories
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter9.Chapter9ViewTests.test_login_form_is_displayed_correctly
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_index_displays_five_most_liked_categories
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter9.Chapter9ViewTests.test_registration_form_is_displayed_correctly
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter5.Chapter5ModelTests.test_create_a_new_category
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter5.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter9.Chapter9ViewTests.test_upload_image
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_add_category_form_is_displayed_correctly
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_index_displays_no_categories_message
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter9.Chapter9ModelTests.test_user_profile_model
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter9.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ModelTests.test_category_contains_slug_field
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_index_context
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_category_context
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_url_reference_in_category_page
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_index_contains_link_to_add_category
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter5.Chapter5ModelTests.test_population_script_changes
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter5.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_link_to_index_in_base_template
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter6.Chapter6ViewTests.test_category_page_displays_category_does_not_exist_message
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter6.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_link_to_add_page_only_appears_in_valid_categories
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter7.Chapter7ViewTests.test_add_page_form_is_displayed_correctly
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter7.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


rango.tests_chapter8.Chapter8ViewTests.test_titles_displayed
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\core\management\commands\test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 600, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "C:\Users\ADAMCH~1\Envs\rango\lib\site-packages\django\test\runner.py", line 484, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "c:\users\adam christie\anaconda2\Lib\unittest\loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "C:\workspace\tango_with_django_project\temporal\rango\tests_chapter8.py", line 12, in <module>
    import populate_rango
  File "C:\workspace\tango_with_django_project\temporal\populate_rango.py", line 25
    ]                                                                                                                                                                                           "url":"http://www.tangowithdjango.com/"} ]
                                                                                                                                                                                                    ^
SyntaxError: invalid syntax
===========================================================================


